version: '3.8'

services:
  backend:
    image: morenodoesinfra/ecommerce-be:latest
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    image: morenodoesinfra/ecommerce-fe:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend