version: '3.8'

services:
  backend:
    image: morenodoesinfra/ecommerce-be:latest
    environment:
      - DB_NAME=your_db_name
      - DB_USER=your_username
      - DB_PASSWORD=your_password
      - DB_HOST=your-rds-endpoint.amazonaws.com
      - DB_PORT=5432
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    image: morenodoesinfra/ecommerce-fe:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    tty: true
    init: true

networks:
  app-network:
    driver: bridge